replicaCount: 3
image:
  repository: pedro1993/helloworld_img
  tag: 1.3
service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

containerPort: 8000
ingress:
  enabled: true  #  ça permet d'activer Ingress
  host: "helloworld.com"  # là on peut mettre le nom de domaine 

