replicaCount: 3
image:
  repository: pedro1993/helloworld_img
  tag: 1.3
service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

containerPort: 8000
ingress:
  enabled: true  # Activer l'Ingress
  host: "avatar.com"  # Nom de domaine pour l'accès à ton application
